appname: "ainur"
entrypoints:
    web:
        cmd: "python web.py"
        ports:
            - "5000/tcp"
    web-host:
        cmd: "python web.py"
        ports:
            - "5000/tcp"
        network_mode: "host"
build: "pip install -r req.txt"
